//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFSoapVendedores
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vendedores", Namespace="http://schemas.datacontract.org/2004/07/MetReciclaWebServiceFinal")]
    public partial class Vendedores : object
    {
        
        private System.Collections.ObjectModel.ObservableCollection<WCFSoapVendedores.TicketCompra> TicketCompraField;
        
        private string direccionField;
        
        private int idvendedorField;
        
        private string nombreField;
        
        private string telefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<WCFSoapVendedores.TicketCompra> TicketCompra
        {
            get
            {
                return this.TicketCompraField;
            }
            set
            {
                this.TicketCompraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccion
        {
            get
            {
                return this.direccionField;
            }
            set
            {
                this.direccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idvendedor
        {
            get
            {
                return this.idvendedorField;
            }
            set
            {
                this.idvendedorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono
        {
            get
            {
                return this.telefonoField;
            }
            set
            {
                this.telefonoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TicketCompra", Namespace="http://schemas.datacontract.org/2004/07/MetReciclaWebServiceFinal")]
    public partial class TicketCompra : object
    {
        
        private System.Collections.ObjectModel.ObservableCollection<WCFSoapVendedores.DetallesCompra> DetallesCompraField;
        
        private System.Collections.ObjectModel.ObservableCollection<WCFSoapVendedores.TotalCompra> TotalCompraField;
        
        private WCFSoapVendedores.Usuarios UsuariosField;
        
        private WCFSoapVendedores.Vendedores VendedoresField;
        
        private System.Nullable<System.DateTime> fechaField;
        
        private int idticketcompraField;
        
        private System.Nullable<int> idusuarioField;
        
        private System.Nullable<int> idvendedorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<WCFSoapVendedores.DetallesCompra> DetallesCompra
        {
            get
            {
                return this.DetallesCompraField;
            }
            set
            {
                this.DetallesCompraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<WCFSoapVendedores.TotalCompra> TotalCompra
        {
            get
            {
                return this.TotalCompraField;
            }
            set
            {
                this.TotalCompraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFSoapVendedores.Usuarios Usuarios
        {
            get
            {
                return this.UsuariosField;
            }
            set
            {
                this.UsuariosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFSoapVendedores.Vendedores Vendedores
        {
            get
            {
                return this.VendedoresField;
            }
            set
            {
                this.VendedoresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idticketcompra
        {
            get
            {
                return this.idticketcompraField;
            }
            set
            {
                this.idticketcompraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idusuario
        {
            get
            {
                return this.idusuarioField;
            }
            set
            {
                this.idusuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idvendedor
        {
            get
            {
                return this.idvendedorField;
            }
            set
            {
                this.idvendedorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuarios", Namespace="http://schemas.datacontract.org/2004/07/MetReciclaWebServiceFinal")]
    public partial class Usuarios : object
    {
        
        private WCFSoapVendedores.Empleados EmpleadosField;
        
        private System.Collections.ObjectModel.ObservableCollection<WCFSoapVendedores.TicketCompra> TicketCompraField;
        
        private System.Collections.ObjectModel.ObservableCollection<WCFSoapVendedores.TicketVenta> TicketVentaField;
        
        private string contraseñaField;
        
        private System.Nullable<int> idempleadoField;
        
        private int idusuarioField;
        
        private string nombreusuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFSoapVendedores.Empleados Empleados
        {
            get
            {
                return this.EmpleadosField;
            }
            set
            {
                this.EmpleadosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<WCFSoapVendedores.TicketCompra> TicketCompra
        {
            get
            {
                return this.TicketCompraField;
            }
            set
            {
                this.TicketCompraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<WCFSoapVendedores.TicketVenta> TicketVenta
        {
            get
            {
                return this.TicketVentaField;
            }
            set
            {
                this.TicketVentaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contraseña
        {
            get
            {
                return this.contraseñaField;
            }
            set
            {
                this.contraseñaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idempleado
        {
            get
            {
                return this.idempleadoField;
            }
            set
            {
                this.idempleadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idusuario
        {
            get
            {
                return this.idusuarioField;
            }
            set
            {
                this.idusuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreusuario
        {
            get
            {
                return this.nombreusuarioField;
            }
            set
            {
                this.nombreusuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetallesCompra", Namespace="http://schemas.datacontract.org/2004/07/MetReciclaWebServiceFinal")]
    public partial class DetallesCompra : object
    {
        
        private WCFSoapVendedores.Chatarra ChatarraField;
        
        private WCFSoapVendedores.TicketCompra TicketCompraField;
        
        private System.Nullable<decimal> cantidadField;
        
        private System.Nullable<int> idchatarraField;
        
        private int iddetallecompraField;
        
        private System.Nullable<int> idticketcompraField;
        
        private System.Nullable<double> subtotalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFSoapVendedores.Chatarra Chatarra
        {
            get
            {
                return this.ChatarraField;
            }
            set
            {
                this.ChatarraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFSoapVendedores.TicketCompra TicketCompra
        {
            get
            {
                return this.TicketCompraField;
            }
            set
            {
                this.TicketCompraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> cantidad
        {
            get
            {
                return this.cantidadField;
            }
            set
            {
                this.cantidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idchatarra
        {
            get
            {
                return this.idchatarraField;
            }
            set
            {
                this.idchatarraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iddetallecompra
        {
            get
            {
                return this.iddetallecompraField;
            }
            set
            {
                this.iddetallecompraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idticketcompra
        {
            get
            {
                return this.idticketcompraField;
            }
            set
            {
                this.idticketcompraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> subtotal
        {
            get
            {
                return this.subtotalField;
            }
            set
            {
                this.subtotalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TotalCompra", Namespace="http://schemas.datacontract.org/2004/07/MetReciclaWebServiceFinal")]
    public partial class TotalCompra : object
    {
        
        private WCFSoapVendedores.TicketCompra TicketCompraField;
        
        private System.Nullable<int> idticketcompraField;
        
        private int idtotalcompraField;
        
        private System.Nullable<int> totalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFSoapVendedores.TicketCompra TicketCompra
        {
            get
            {
                return this.TicketCompraField;
            }
            set
            {
                this.TicketCompraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idticketcompra
        {
            get
            {
                return this.idticketcompraField;
            }
            set
            {
                this.idticketcompraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idtotalcompra
        {
            get
            {
                return this.idtotalcompraField;
            }
            set
            {
                this.idtotalcompraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> total
        {
            get
            {
                return this.totalField;
            }
            set
            {
                this.totalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Chatarra", Namespace="http://schemas.datacontract.org/2004/07/MetReciclaWebServiceFinal")]
    public partial class Chatarra : object
    {
        
        private System.Collections.ObjectModel.ObservableCollection<WCFSoapVendedores.DetallesCompra> DetallesCompraField;
        
        private System.Collections.ObjectModel.ObservableCollection<WCFSoapVendedores.PrecioVenta> PrecioVentaField;
        
        private int idchatarraField;
        
        private string nombreField;
        
        private System.Nullable<int> preciocompraField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<WCFSoapVendedores.DetallesCompra> DetallesCompra
        {
            get
            {
                return this.DetallesCompraField;
            }
            set
            {
                this.DetallesCompraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<WCFSoapVendedores.PrecioVenta> PrecioVenta
        {
            get
            {
                return this.PrecioVentaField;
            }
            set
            {
                this.PrecioVentaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idchatarra
        {
            get
            {
                return this.idchatarraField;
            }
            set
            {
                this.idchatarraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> preciocompra
        {
            get
            {
                return this.preciocompraField;
            }
            set
            {
                this.preciocompraField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrecioVenta", Namespace="http://schemas.datacontract.org/2004/07/MetReciclaWebServiceFinal")]
    public partial class PrecioVenta : object
    {
        
        private WCFSoapVendedores.Chatarra ChatarraField;
        
        private System.Collections.ObjectModel.ObservableCollection<WCFSoapVendedores.DetallesVenta> DetallesVentaField;
        
        private WCFSoapVendedores.LocalVenta LocalVentaField;
        
        private System.Nullable<int> idchatarraField;
        
        private System.Nullable<int> idlocalventaField;
        
        private int idprecioventaField;
        
        private System.Nullable<int> precioventa1Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFSoapVendedores.Chatarra Chatarra
        {
            get
            {
                return this.ChatarraField;
            }
            set
            {
                this.ChatarraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<WCFSoapVendedores.DetallesVenta> DetallesVenta
        {
            get
            {
                return this.DetallesVentaField;
            }
            set
            {
                this.DetallesVentaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFSoapVendedores.LocalVenta LocalVenta
        {
            get
            {
                return this.LocalVentaField;
            }
            set
            {
                this.LocalVentaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idchatarra
        {
            get
            {
                return this.idchatarraField;
            }
            set
            {
                this.idchatarraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idlocalventa
        {
            get
            {
                return this.idlocalventaField;
            }
            set
            {
                this.idlocalventaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idprecioventa
        {
            get
            {
                return this.idprecioventaField;
            }
            set
            {
                this.idprecioventaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> precioventa1
        {
            get
            {
                return this.precioventa1Field;
            }
            set
            {
                this.precioventa1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocalVenta", Namespace="http://schemas.datacontract.org/2004/07/MetReciclaWebServiceFinal")]
    public partial class LocalVenta : object
    {
        
        private System.Collections.ObjectModel.ObservableCollection<WCFSoapVendedores.PrecioVenta> PrecioVentaField;
        
        private string direccionField;
        
        private int idlocalventaField;
        
        private string nombreField;
        
        private string telefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<WCFSoapVendedores.PrecioVenta> PrecioVenta
        {
            get
            {
                return this.PrecioVentaField;
            }
            set
            {
                this.PrecioVentaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccion
        {
            get
            {
                return this.direccionField;
            }
            set
            {
                this.direccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idlocalventa
        {
            get
            {
                return this.idlocalventaField;
            }
            set
            {
                this.idlocalventaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono
        {
            get
            {
                return this.telefonoField;
            }
            set
            {
                this.telefonoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetallesVenta", Namespace="http://schemas.datacontract.org/2004/07/MetReciclaWebServiceFinal")]
    public partial class DetallesVenta : object
    {
        
        private WCFSoapVendedores.PrecioVenta PrecioVentaField;
        
        private WCFSoapVendedores.TicketVenta TicketVentaField;
        
        private System.Nullable<decimal> cantidadField;
        
        private int iddetallesventaField;
        
        private System.Nullable<int> idprecioventaField;
        
        private System.Nullable<int> idticketventaField;
        
        private System.Nullable<int> subtotalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFSoapVendedores.PrecioVenta PrecioVenta
        {
            get
            {
                return this.PrecioVentaField;
            }
            set
            {
                this.PrecioVentaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFSoapVendedores.TicketVenta TicketVenta
        {
            get
            {
                return this.TicketVentaField;
            }
            set
            {
                this.TicketVentaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> cantidad
        {
            get
            {
                return this.cantidadField;
            }
            set
            {
                this.cantidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iddetallesventa
        {
            get
            {
                return this.iddetallesventaField;
            }
            set
            {
                this.iddetallesventaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idprecioventa
        {
            get
            {
                return this.idprecioventaField;
            }
            set
            {
                this.idprecioventaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idticketventa
        {
            get
            {
                return this.idticketventaField;
            }
            set
            {
                this.idticketventaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> subtotal
        {
            get
            {
                return this.subtotalField;
            }
            set
            {
                this.subtotalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TicketVenta", Namespace="http://schemas.datacontract.org/2004/07/MetReciclaWebServiceFinal")]
    public partial class TicketVenta : object
    {
        
        private System.Collections.ObjectModel.ObservableCollection<WCFSoapVendedores.DetallesVenta> DetallesVentaField;
        
        private System.Collections.ObjectModel.ObservableCollection<WCFSoapVendedores.TotalVenta> TotalVentaField;
        
        private WCFSoapVendedores.Usuarios UsuariosField;
        
        private System.Nullable<System.DateTime> fechaField;
        
        private int idticketventaField;
        
        private System.Nullable<int> idusuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<WCFSoapVendedores.DetallesVenta> DetallesVenta
        {
            get
            {
                return this.DetallesVentaField;
            }
            set
            {
                this.DetallesVentaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<WCFSoapVendedores.TotalVenta> TotalVenta
        {
            get
            {
                return this.TotalVentaField;
            }
            set
            {
                this.TotalVentaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFSoapVendedores.Usuarios Usuarios
        {
            get
            {
                return this.UsuariosField;
            }
            set
            {
                this.UsuariosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idticketventa
        {
            get
            {
                return this.idticketventaField;
            }
            set
            {
                this.idticketventaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idusuario
        {
            get
            {
                return this.idusuarioField;
            }
            set
            {
                this.idusuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TotalVenta", Namespace="http://schemas.datacontract.org/2004/07/MetReciclaWebServiceFinal")]
    public partial class TotalVenta : object
    {
        
        private WCFSoapVendedores.TicketVenta TicketVentaField;
        
        private System.Nullable<int> idticketventaField;
        
        private int idtotalventaField;
        
        private System.Nullable<int> totalventa1Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFSoapVendedores.TicketVenta TicketVenta
        {
            get
            {
                return this.TicketVentaField;
            }
            set
            {
                this.TicketVentaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idticketventa
        {
            get
            {
                return this.idticketventaField;
            }
            set
            {
                this.idticketventaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idtotalventa
        {
            get
            {
                return this.idtotalventaField;
            }
            set
            {
                this.idtotalventaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> totalventa1
        {
            get
            {
                return this.totalventa1Field;
            }
            set
            {
                this.totalventa1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empleados", Namespace="http://schemas.datacontract.org/2004/07/MetReciclaWebServiceFinal")]
    public partial class Empleados : object
    {
        
        private System.Collections.ObjectModel.ObservableCollection<WCFSoapVendedores.Usuarios> UsuariosField;
        
        private string apellidoField;
        
        private string cedulaField;
        
        private string contraseñaField;
        
        private string direccionField;
        
        private int idempleadoField;
        
        private string nombreField;
        
        private string telefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<WCFSoapVendedores.Usuarios> Usuarios
        {
            get
            {
                return this.UsuariosField;
            }
            set
            {
                this.UsuariosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellido
        {
            get
            {
                return this.apellidoField;
            }
            set
            {
                this.apellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cedula
        {
            get
            {
                return this.cedulaField;
            }
            set
            {
                this.cedulaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contraseña
        {
            get
            {
                return this.contraseñaField;
            }
            set
            {
                this.contraseñaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccion
        {
            get
            {
                return this.direccionField;
            }
            set
            {
                this.direccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idempleado
        {
            get
            {
                return this.idempleadoField;
            }
            set
            {
                this.idempleadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono
        {
            get
            {
                return this.telefonoField;
            }
            set
            {
                this.telefonoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VendedoresDc", Namespace="http://schemas.datacontract.org/2004/07/MetReciclaWebServiceFinal")]
    public partial class VendedoresDc : object
    {
        
        private string DireccionField;
        
        private int IdvendedorField;
        
        private string NombreField;
        
        private string TelefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion
        {
            get
            {
                return this.DireccionField;
            }
            set
            {
                this.DireccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Idvendedor
        {
            get
            {
                return this.IdvendedorField;
            }
            set
            {
                this.IdvendedorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFSoapVendedores.VendedoresSoap")]
    public interface VendedoresSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VendedoresSoap/ListaVendedores", ReplyAction="http://tempuri.org/VendedoresSoap/ListaVendedoresResponse")]
        System.Collections.ObjectModel.ObservableCollection<WCFSoapVendedores.Vendedores> ListaVendedores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VendedoresSoap/ListaVendedores", ReplyAction="http://tempuri.org/VendedoresSoap/ListaVendedoresResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<WCFSoapVendedores.Vendedores>> ListaVendedoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VendedoresSoap/AgregarVendedores", ReplyAction="http://tempuri.org/VendedoresSoap/AgregarVendedoresResponse")]
        bool AgregarVendedores(WCFSoapVendedores.VendedoresDc vendedoresDc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VendedoresSoap/AgregarVendedores", ReplyAction="http://tempuri.org/VendedoresSoap/AgregarVendedoresResponse")]
        System.Threading.Tasks.Task<bool> AgregarVendedoresAsync(WCFSoapVendedores.VendedoresDc vendedoresDc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VendedoresSoap/ActualizarVendedores", ReplyAction="http://tempuri.org/VendedoresSoap/ActualizarVendedoresResponse")]
        bool ActualizarVendedores(WCFSoapVendedores.VendedoresDc vendedoresDc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VendedoresSoap/ActualizarVendedores", ReplyAction="http://tempuri.org/VendedoresSoap/ActualizarVendedoresResponse")]
        System.Threading.Tasks.Task<bool> ActualizarVendedoresAsync(WCFSoapVendedores.VendedoresDc vendedoresDc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VendedoresSoap/EliminarVendedores", ReplyAction="http://tempuri.org/VendedoresSoap/EliminarVendedoresResponse")]
        bool EliminarVendedores(WCFSoapVendedores.VendedoresDc vendedoresDc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VendedoresSoap/EliminarVendedores", ReplyAction="http://tempuri.org/VendedoresSoap/EliminarVendedoresResponse")]
        System.Threading.Tasks.Task<bool> EliminarVendedoresAsync(WCFSoapVendedores.VendedoresDc vendedoresDc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VendedoresSoap/ObtenerVendedores", ReplyAction="http://tempuri.org/VendedoresSoap/ObtenerVendedoresResponse")]
        WCFSoapVendedores.VendedoresDc ObtenerVendedores(int idVendedores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VendedoresSoap/ObtenerVendedores", ReplyAction="http://tempuri.org/VendedoresSoap/ObtenerVendedoresResponse")]
        System.Threading.Tasks.Task<WCFSoapVendedores.VendedoresDc> ObtenerVendedoresAsync(int idVendedores);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface VendedoresSoapChannel : WCFSoapVendedores.VendedoresSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class VendedoresSoapClient : System.ServiceModel.ClientBase<WCFSoapVendedores.VendedoresSoap>, WCFSoapVendedores.VendedoresSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public VendedoresSoapClient() : 
                base(VendedoresSoapClient.GetDefaultBinding(), VendedoresSoapClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_VendedoresSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VendedoresSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(VendedoresSoapClient.GetBindingForEndpoint(endpointConfiguration), VendedoresSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VendedoresSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(VendedoresSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VendedoresSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(VendedoresSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VendedoresSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.ObjectModel.ObservableCollection<WCFSoapVendedores.Vendedores> ListaVendedores()
        {
            return base.Channel.ListaVendedores();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<WCFSoapVendedores.Vendedores>> ListaVendedoresAsync()
        {
            return base.Channel.ListaVendedoresAsync();
        }
        
        public bool AgregarVendedores(WCFSoapVendedores.VendedoresDc vendedoresDc)
        {
            return base.Channel.AgregarVendedores(vendedoresDc);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarVendedoresAsync(WCFSoapVendedores.VendedoresDc vendedoresDc)
        {
            return base.Channel.AgregarVendedoresAsync(vendedoresDc);
        }
        
        public bool ActualizarVendedores(WCFSoapVendedores.VendedoresDc vendedoresDc)
        {
            return base.Channel.ActualizarVendedores(vendedoresDc);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarVendedoresAsync(WCFSoapVendedores.VendedoresDc vendedoresDc)
        {
            return base.Channel.ActualizarVendedoresAsync(vendedoresDc);
        }
        
        public bool EliminarVendedores(WCFSoapVendedores.VendedoresDc vendedoresDc)
        {
            return base.Channel.EliminarVendedores(vendedoresDc);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarVendedoresAsync(WCFSoapVendedores.VendedoresDc vendedoresDc)
        {
            return base.Channel.EliminarVendedoresAsync(vendedoresDc);
        }
        
        public WCFSoapVendedores.VendedoresDc ObtenerVendedores(int idVendedores)
        {
            return base.Channel.ObtenerVendedores(idVendedores);
        }
        
        public System.Threading.Tasks.Task<WCFSoapVendedores.VendedoresDc> ObtenerVendedoresAsync(int idVendedores)
        {
            return base.Channel.ObtenerVendedoresAsync(idVendedores);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_VendedoresSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_VendedoresSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:53209/VendedoresSoap.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return VendedoresSoapClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_VendedoresSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return VendedoresSoapClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_VendedoresSoap);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_VendedoresSoap,
        }
    }
}
